name: "Kubeval"
description: "Validate Kubernetes manifests using the upstream Schemas"
author: "Gareth Rushgrove"
branding:
  icon: "check"
  color: "green"
inputs: 
  files:
    description: "Files or directories to validate"
    default: "."
outputs:
  all:
    description: "All validation results"
runs:
  using: 'docker'
  image: 'docker://marcleibold/kubeval:latest'
  args:
  - -d
  - ${{ inputs.files }} 

